# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: common
generate:
  models: true
  embedded-spec: true
output-options:
  skip-prune: true
output: internal/generated/api/common/types.go
