// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	users "github.com/naceto/tempstation/internal/generated/api/users"
	models "github.com/naceto/tempstation/internal/storage/models"
)

type ConvertImpl struct{}

func (c *ConvertImpl) CreateUserAPIToStorage(source *users.PostV1UsersRequestObject) *models.CreateUser {
	var pModelsCreateUser *models.CreateUser
	if source != nil {
		var modelsCreateUser models.CreateUser
		var pString *string
		if (*source).Body != nil {
			pString = &(*source).Body.Name
		}
		if pString != nil {
			modelsCreateUser.Name = *pString
		}
		var pString2 *string
		if (*source).Body != nil {
			pString2 = &(*source).Body.Email
		}
		if pString2 != nil {
			modelsCreateUser.Email = *pString2
		}
		pModelsCreateUser = &modelsCreateUser
	}
	return pModelsCreateUser
}
func (c *ConvertImpl) GetUserAPIFromStorage(source *models.User) *users.GetV1UsersId200JSONResponse {
	var pApiGetV1UsersId200JSONResponse *users.GetV1UsersId200JSONResponse
	if source != nil {
		var apiGetV1UsersId200JSONResponse users.GetV1UsersId200JSONResponse
		apiGetV1UsersId200JSONResponse.UserResponseJSONResponse = c.UserAPIFromStorageEmbedded((*source))
		pApiGetV1UsersId200JSONResponse = &apiGetV1UsersId200JSONResponse
	}
	return pApiGetV1UsersId200JSONResponse
}
func (c *ConvertImpl) ListUsersAPIFromStorage(source []*models.User) users.GetV1Users200JSONResponse {
	return ListUsersAPIFromStorageExtend(source)
}
func (c *ConvertImpl) ListUsersAPIToStorage(source *users.GetV1UsersRequestObject) *models.ListUsersParams {
	var pModelsListUsersParams *models.ListUsersParams
	if source != nil {
		var modelsListUsersParams models.ListUsersParams
		if (*source).Params.Limit != nil {
			modelsListUsersParams.Limit = *(*source).Params.Limit
		}
		if (*source).Params.Offset != nil {
			modelsListUsersParams.Offset = *(*source).Params.Offset
		}
		pModelsListUsersParams = &modelsListUsersParams
	}
	return pModelsListUsersParams
}
func (c *ConvertImpl) PostUserAPIFromStorage(source *models.User) *users.PostV1Users200JSONResponse {
	var pApiPostV1Users200JSONResponse *users.PostV1Users200JSONResponse
	if source != nil {
		var apiPostV1Users200JSONResponse users.PostV1Users200JSONResponse
		apiPostV1Users200JSONResponse.UserResponseJSONResponse = c.UserAPIFromStorageEmbedded((*source))
		pApiPostV1Users200JSONResponse = &apiPostV1Users200JSONResponse
	}
	return pApiPostV1Users200JSONResponse
}
func (c *ConvertImpl) UserAPIFromStorageEmbedded(source models.User) users.UserResponseJSONResponse {
	var apiUserResponseJSONResponse users.UserResponseJSONResponse
	pString := source.Email
	apiUserResponseJSONResponse.Email = &pString
	pInt64 := source.ID
	apiUserResponseJSONResponse.Id = &pInt64
	pString2 := source.Name
	apiUserResponseJSONResponse.Name = &pString2
	return apiUserResponseJSONResponse
}
