// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package convert

import (
	db "github.com/naceto/tempstation/internal/generated/db"
	models "github.com/naceto/tempstation/internal/storage/models"
)

type ConvertImpl struct{}

func (c *ConvertImpl) CreateUserModelToDB(source *models.CreateUser) db.CreateUserParams {
	var dbCreateUserParams db.CreateUserParams
	if source != nil {
		var dbCreateUserParams2 db.CreateUserParams
		dbCreateUserParams2.Name = (*source).Name
		dbCreateUserParams2.Email = (*source).Email
		dbCreateUserParams = dbCreateUserParams2
	}
	return dbCreateUserParams
}
func (c *ConvertImpl) UserModelFromDB(source db.User) *models.User {
	var modelsUser models.User
	modelsUser.ID = source.ID
	modelsUser.Name = source.Name
	modelsUser.Email = source.Email
	return &modelsUser
}
func (c *ConvertImpl) UserModelsFromDB(source []db.User) []*models.User {
	var pModelsUserList []*models.User
	if source != nil {
		pModelsUserList = make([]*models.User, len(source))
		for i := 0; i < len(source); i++ {
			pModelsUserList[i] = c.UserModelFromDB(source[i])
		}
	}
	return pModelsUserList
}
