components:
  responses:
    ErrorResponse:
      description: Error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      description: Error is a standard error response.
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer

    ID:
      description: The resource's ID.
      type: integer
      format: int64
