openapi: "3.0.0"
info:
  version: 1.0.0
  title: Tempstation API
tags:
  - name: sensors
    description: Sensor endpoints

paths:
  /v1/sensors:
    get:
      tags:
        - sensors
      responses:
        "200":
          $ref: "#/components/responses/SensorsDataResponse"
        "400":
          $ref: "../common/openapi.yaml#/components/responses/ErrorResponse"
        "500":
          $ref: "../common/openapi.yaml#/components/responses/ErrorResponse"
    post:
      tags:
        - sensors
      requestBody:
        $ref: "#/components/requestBodies/SensorPost"
      responses:
        "200":
          $ref: "#/components/responses/SensorResponse"
        "400":
          $ref: "../common/openapi.yaml#/components/responses/ErrorResponse"
        "500":
          $ref: "../common/openapi.yaml#/components/responses/ErrorResponse"

components:
  requestBodies:
    SensorPost:
      description: The new sensor data to add.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SensorPost"

  responses:
    SensorResponse:
      description: Sensor info.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Sensor"

    SensorsDataResponse:
      description: Sensors response.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SensorsDataResponse"

  schemas:
    Error:
      $ref: "../common/openapi.yaml#/components/schemas/Error"
    Sensor:
      type: object
      description: Sensor specific information.
      required:
        - id
        - userId
        - name
        - mac
        - type
      properties:
        id:
          $ref: "../common/openapi.yaml#/components/schemas/ID"
        userId:
          $ref: "../common/openapi.yaml#/components/schemas/ID"
        name:
          type: string
        mac:
          type: string
        type:
          $ref: "#/components/schemas/SensorType"

    SensorPost:
      type: object
      description: Sensor specific information.
      required:
        - userId
        - name
        - mac
        - type
      properties:
        userId:
          $ref: "../common/openapi.yaml#/components/schemas/ID"
        name:
          type: string
        mac:
          type: string
        type:
          $ref: "#/components/schemas/SensorType"

    SensorType:
      description: Sensor type.
      type: string
      enum:
        - DHT11
        - DHT22

    SensorsDataResponse:
      type: object
      description: List of sensor data.
      required:
        - sensors
      properties:
        sensors:
          type: array
          items:
            $ref: "#/components/schemas/SensorData"

    SensorData:
      type: object
      description: Sensor climate data.
      properties:
        id:
          type: integer
          format: int64
        sensorId:
          type: integer
          format: int64
        temperature:
          type: number
          format: float
        humidity:
          type: number
          format: float
        readingTime:
          type: string
          format: date-time
